name: jamat_time
description: "A Flutter project for tracking mosque prayer times with an Islamic theme."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  hijri: ^3.0.0
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  blur: ^3.1.0 # For the glass effect

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700