name: jamat_time
description: A modern, professional Flutter application for Islamic prayer times and tools.
publish_to: 'none' 
version: 3.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.20.2
  hijri: ^3.0.0
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  shared_preferences: ^2.2.3
  http: ^1.2.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  image: ^4.1.7

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  adaptive_icon_background: "#006A71"
  adaptive_icon_foreground: assets/icon/app_icon.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/icon/app_icon.png
    background_color: "#F0F5F9"
    theme_color: "#006A71"
  windows:
    generate: true
    image_path: assets/icon/app_icon.png
  macos:
    generate: true
    image_path: assets/icon/app_icon.png
