name: jamat_time
description: A modern, professional Flutter application for Islamic prayer times and tools.
publish_to: 'none' 
version: 3.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.19.0
  hijri: ^3.0.0
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true